name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean-compile-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Clean, compile and test
        run: mvn -B clean compile test
 
  pmd-analysis:
    runs-on: ubuntu-latest
    needs: clean-compile-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run PMD static analysis
        run: mvn -B pmd:pmd

  jacoco-report:
    runs-on: ubuntu-latest
    needs: clean-compile-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate Jacoco report
        run: mvn -B jacoco:report

  build:
    runs-on: ubuntu-latest
    needs: [clean-compile-test, pmd-analysis, jacoco-report]

    steps:
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

      - name: Upload PMD report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: target/site/pmd/pmd.xml
